# Ecrire un Github actions qui utilise un Dockerfile pour build une image et la pousser sur le Docker hub. Il se déclenche un push sur la branche main

name: Github Actions Demo
on: [push]
jobs: 
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
    
      #checkout the code
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      # Log in to Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3.3.0
        with :
               username: ${{ secrets.Username }}
               password: ${{ secrets.Password }}
      # Build and Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with: 
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          
        
      
      
      
