# Ecrire un Github actions qui utilise un Dockerfile pour build une image et la pousser sur le Docker hub. Il se déclenche un push sur la branche main

name: Github Actions Demo
on: [push]
jobs: 
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
    
      #checkout the code
      -name: Check
       uses: actions/checkout
       
      # Log in to Docker Hub
      -name: Login Docker Hub
       uses: docker/login-action
      with:
          username: ${{ secrets.BioLAB }}
          password: ${{ secrets.BioLAB123 }}
          
      # Build Docker image
       - name: Build Docker image
        run: docker build -t ${{ secrets.BioLAB }}/The-Image:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.BioLAB }}/The-Image:latest
        
      
      
      
